name: my_flutter_monorepo

packages:
  - application
  - core
  - shared
  - features/*

scripts:
  # Run all tests in the monorepo
  test: |
  # FLAVOR: staging
  run:debug:staging: cd application && flutter run --flavor staging -t lib/main_staging.dart --debug
  run:release:staging: cd application && flutter run --flavor staging -t lib/main_staging.dart --release

  # FLAVOR: production
  run:debug:production: cd application && flutter run --flavor production -t lib/main_production.dart --debug
  run:release:production: cd application && flutter run --flavor production -t lib/main_production.dart --release
# Build staging / production APK release
  build:staging:apk:
    run: cd application && flutter build apk --flavor staging -t lib/main_staging.dart --release --obfuscate --split-debug-info=out/staging
    description: Build staging APK (release)

  build:production:apk:
    run: cd application && flutter build apk --flavor production -t lib/main_production.dart --release --obfuscate --split-debug-info=out/production
    description: Build production APK (release)

  # Optional: Build iOS
  build:staging:ios:
    run: cd application && flutter build ios --flavor staging -t lib/main_staging.dart
    description: Build iOS staging
  
  # Optional: Build iOS staging
  build:staging:ipa:
    run: cd application && flutter build ipa --flavor staging -t lib/main_staging.dart --obfuscate --split-debug-info=out/staging
    description: Build iOS staging

  # Optional: Build iOS  production
  build:production:ios:
    run: cd application && flutter build ios --flavor production -t lib/main_production.dart
    description: Build iOS production
  
  # Optional: Build iOS production
  build:production:ipa:
    run: cd application && flutter build ipa --flavor production -t lib/main_production.dart --obfuscate --split-debug-info=out/production
    description: Build iOS production
  
  