name: core
publish_to: none
environment:
   sdk: ^3.8.0
   flutter: 3.32.0

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.4
  get_it: ^8.0.3
  dio: ^5.8.0+1
  chucker_flutter: ^1.8.5
  logging: ^1.3.0
  cote_network_logger: ^1.2.0
  sentry_flutter: ^9.1.0
  pretty_dio_logger: ^1.4.0
  equatable: ^2.0.7
  flutter_secure_storage: ^9.2.4
  go_router: ^15.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0
