name: shared
publish_to: none
environment:
   sdk: ^3.8.0
   flutter: 3.32.0

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core

  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  dio: ^5.8.0+1
  logging: ^1.3.0
  intl: ^0.20.2
  go_router: ^15.2.4
  json_theme: ^9.0.1+1
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0
  mockito: ^5.4.6

flutter:
  generate: true


  assets:
    - assets/themes/


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
    
